module.exports.descriptors = [
    "forest",
    "Ancient",
    "Roaring",
    "Cascade",
    "tumbling",
    "silent",
    "Redwood",
    "bullfrog",
    "Maple",
    "misty",
    "elk",
    "grizzly",
    "ocean",
    "Sea",
    "Sky",
    "Dusty",
    "Diamond"
],

module.exports.places = [
    "flats",
    "village",
    "canyon",
    "group camp",
    "horse camp",
    "ghost camp",
    "group camp",
    "camp",
    "dispersed camp",
    "river",
    "creek",
    "creekside",
    "bay",
    "spring",
    "bayshore",
    "sands",
    "wilkins",
]